"""
train_model.py  v3
------------------
Trains on features extracted directly from IMAGE FILES using the same
feature_extractor.py used at inference time — so scales always match.

The CSV is used ONLY for labels (CLASS_TYPE), not for feature values.

Two data sources:
  1. Labelled images in --imgs folder (matched to CSV by filename)
  2. Synthetic augmentation: PD images generated by perturbing healthy images

Usage
-----
    python train_model.py --csv Spiral_HandPD.csv --imgs images/ --out models/rf_model.pkl

If you have no images folder, run with --synth-only to train on
synthetically augmented versions of one or more sample images you provide.
"""

import os
import argparse
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
from pathlib import Path
import joblib
import cv2

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, accuracy_score

from feature_extractor import extract_features, FEATURE_COLS

LABEL_MAP = {1: 1, 2: 0}   # 1=PD → 1,  2=Healthy → 0


# ────────────────────────────────────────────────────────────────────────────
# Augmentation helpers
# ────────────────────────────────────────────────────────────────────────────

def augment_healthy(img: np.ndarray, n: int = 5) -> list:
    """Return n augmented versions of a healthy image (minor perturbations)."""
    imgs = []
    for _ in range(n):
        out = img.copy().astype(float)
        # Small brightness/contrast jitter
        alpha = np.random.uniform(0.90, 1.10)
        beta  = np.random.randint(-10, 10)
        out   = np.clip(out * alpha + beta, 0, 255).astype(np.uint8)
        # Slight rotation
        angle = np.random.uniform(-5, 5)
        M     = cv2.getRotationMatrix2D((img.shape[1]//2, img.shape[0]//2), angle, 1)
        out   = cv2.warpAffine(out, M, (img.shape[1], img.shape[0]))
        imgs.append(out)
    return imgs


def augment_pd(img: np.ndarray, n: int = 5) -> list:
    """
    Return n PD-like augmented versions of an image.
    Simulates tremor: adds noise, blurring, slight warp to mimic
    the irregular strokes seen in Parkinson's patients.
    """
    imgs = []
    for _ in range(n):
        out = img.copy()
        gray = cv2.cvtColor(out, cv2.COLOR_BGR2GRAY) if len(out.shape)==3 else out.copy()

        # Add salt-and-pepper noise (simulates tremor dots)
        noise_mask = np.random.random(gray.shape)
        gray[noise_mask < 0.03] = 255
        gray[noise_mask > 0.97] = 0

        # Elastic-style random displacement (simulates shaky lines)
        dx = cv2.GaussianBlur(np.random.randn(*gray.shape).astype(np.float32), (15,15), 0) * 3
        dy = cv2.GaussianBlur(np.random.randn(*gray.shape).astype(np.float32), (15,15), 0) * 3
        x, y = np.meshgrid(np.arange(gray.shape[1]), np.arange(gray.shape[0]))
        map_x = np.clip(x + dx, 0, gray.shape[1]-1).astype(np.float32)
        map_y = np.clip(y + dy, 0, gray.shape[0]-1).astype(np.float32)
        out_gray = cv2.remap(gray, map_x, map_y, cv2.INTER_LINEAR)

        # Slight blur (reduced pen control)
        k = np.random.choice([3, 5])
        out_gray = cv2.GaussianBlur(out_gray, (k, k), 0)

        # Back to BGR
        out_bgr = cv2.cvtColor(out_gray, cv2.COLOR_GRAY2BGR)
        imgs.append(out_bgr)
    return imgs


# ────────────────────────────────────────────────────────────────────────────
# 1. Extract features from labelled images
# ────────────────────────────────────────────────────────────────────────────
def load_from_images(img_dir: str, csv_path: str):
    df        = pd.read_csv(csv_path)
    label_lut = dict(zip(df["IMAGE_NAME"], df["CLASS_TYPE"].map(LABEL_MAP)))

    img_dir = Path(img_dir)
    rows    = []
    missing = 0

    for ext in ("*.jpg","*.jpeg","*.png","*.JPG","*.JPEG","*.PNG"):
        for fpath in sorted(img_dir.glob(ext)):
            fname = fpath.name
            if fname not in label_lut:
                continue
            label = label_lut[fname]
            img   = cv2.imread(str(fpath))
            if img is None:
                missing += 1
                continue

            # Original image
            feats = extract_features(img)
            if feats:
                feats["label"] = label
                feats["source"] = "original"
                rows.append(feats)

            # Augment — 4 more per image (healthy augmentations)
            for aug in augment_healthy(img, n=4):
                f = extract_features(aug)
                if f:
                    f["label"]  = label
                    f["source"] = "aug_healthy"
                    rows.append(f)

            # If healthy image → also generate PD variants for balance
            if label == 0:
                for aug in augment_pd(img, n=4):
                    f = extract_features(aug)
                    if f:
                        f["label"]  = 1
                        f["source"] = "aug_pd"
                        rows.append(f)

    df_out = pd.DataFrame(rows)
    pd_n   = int((df_out["label"]==1).sum()) if len(df_out) else 0
    hlt_n  = int((df_out["label"]==0).sum()) if len(df_out) else 0
    print(f"[IMG]  Extracted from {len(rows)} image rows  |  PD={pd_n}  Healthy={hlt_n}  (missing={missing})")
    return df_out


# ────────────────────────────────────────────────────────────────────────────
# 2. Fallback: synth-only mode using provided sample images
# ────────────────────────────────────────────────────────────────────────────
def synth_only_dataset(sample_imgs: list, n_per_class: int = 300):
    """
    When no labelled image folder exists, generate training data by:
      - treating provided images as healthy
      - generating PD variants via augmentation
    """
    rows = []
    for path in sample_imgs:
        img = cv2.imread(path)
        if img is None:
            print(f"[WARN] Could not read {path}")
            continue
        # Healthy variants
        for aug in augment_healthy(img, n=n_per_class // max(len(sample_imgs),1)):
            f = extract_features(aug)
            if f:
                f["label"]  = 0
                f["source"] = "synth_healthy"
                rows.append(f)
        # PD variants
        for aug in augment_pd(img, n=n_per_class // max(len(sample_imgs),1)):
            f = extract_features(aug)
            if f:
                f["label"]  = 1
                f["source"] = "synth_pd"
                rows.append(f)

    df = pd.DataFrame(rows)
    print(f"[SYNTH] Generated {len(df)} rows  |  PD={(df['label']==1).sum()}  Healthy={(df['label']==0).sum()}")
    return df


# ────────────────────────────────────────────────────────────────────────────
# 3. Train
# ────────────────────────────────────────────────────────────────────────────
def train(dataset: pd.DataFrame, out_path: str):
    dataset = dataset.dropna(subset=FEATURE_COLS + ["label"])

    if len(dataset) < 20:
        print(f"[ERROR] Only {len(dataset)} usable rows — need at least 20. "
              "Check your images folder or use --synth-only with sample images.")
        return None

    X = dataset[FEATURE_COLS].values
    y = dataset["label"].values.astype(int)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    pipeline = Pipeline([
        ("scaler", StandardScaler()),
        ("clf", RandomForestClassifier(
            n_estimators=300,
            max_depth=12,
            min_samples_leaf=3,
            class_weight="balanced",
            random_state=42,
            n_jobs=-1
        ))
    ])

    cv        = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    cv_scores = cross_val_score(pipeline, X_train, y_train, cv=cv, scoring="roc_auc")
    print(f"\n[TRAIN] 5-Fold CV AUC : {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")

    pipeline.fit(X_train, y_train)

    y_pred = pipeline.predict(X_test)
    y_prob = pipeline.predict_proba(X_test)[:, 1]
    acc    = accuracy_score(y_test, y_pred)
    auc    = roc_auc_score(y_test, y_prob)

    print(f"[TEST]  Accuracy : {acc:.4f}")
    print(f"[TEST]  ROC-AUC  : {auc:.4f}")
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred, target_names=["Healthy","Parkinson's"]))
    print("Confusion Matrix (rows=actual, cols=predicted):")
    print(confusion_matrix(y_test, y_pred))

    rf          = pipeline.named_steps["clf"]
    importances = pd.Series(rf.feature_importances_, index=FEATURE_COLS).sort_values(ascending=False)
    print("\nFeature Importances:")
    print(importances.to_string())

    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    model_meta = {
        "pipeline":      pipeline,
        "train_accuracy": acc,
        "train_auc":      auc,
        "cv_auc_mean":    float(cv_scores.mean()),
        "cv_auc_std":     float(cv_scores.std()),
        "n_train":        len(X_train),
        "n_test":         len(X_test),
        "n_pd":           int(y.sum()),
        "n_healthy":      int((y==0).sum()),
        "feature_cols":   FEATURE_COLS,
    }
    joblib.dump(model_meta, out_path)
    print(f"\n✅  Model saved → {out_path}")
    return pipeline


# ────────────────────────────────────────────────────────────────────────────
# 4. Entry point
# ────────────────────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(description="Train NeuroGraph RF model v3")
    parser.add_argument("--csv",        default="Spiral_HandPD.csv")
    parser.add_argument("--imgs",       default="images",
                        help="Folder with labelled spiral images")
    parser.add_argument("--out",        default="models/rf_model.pkl")
    parser.add_argument("--synth-only", nargs="+", metavar="IMAGE",
                        help="Skip labelled images; generate synth data from these sample images")
    args = parser.parse_args()

    print("=" * 60)
    print("  NeuroGraph — Training Pipeline v3")
    print("=" * 60)

    if args.synth_only:
        print(f"[MODE] Synth-only from: {args.synth_only}")
        dataset = synth_only_dataset(args.synth_only, n_per_class=300)
    else:
        print(f"[MODE] Image extraction from: {args.imgs}")
        dataset = load_from_images(args.imgs, args.csv)

        if len(dataset) == 0:
            print("[WARN] No labelled images found in folder. "
                  "Use --synth-only <image1.jpg> <image2.jpg> to train without a labelled folder.")
            return

    train(dataset, args.out)


if __name__ == "__main__":
    main()
